name: Release Creation

env:
  project_url: "https://github.com/${{github.repository}}"
  latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/module.json"
  release_module_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip"

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Extract Version from Tag
      id: get_version
      uses: battila7/get-version-action@v2

    # Install Pack Compilation Dependencies
    - name: Install Dependencies
      run: npm install @foundryvtt/foundryvtt-cli

    # Build the Release
    - name: Build
      run: node ./build-scripts/build-packs.js

    # Combine the individual trigger files into the final file
    - name: Build Trigger File
      run: node ./build-scripts/combine-triggers.js

    # Modify module.json as appropriate
    - name: Modify Module Manifest with specific values
      id: sub_manifest_link_version
      uses: cschleiden/replace-tokens@v1
      with:
        files: "module.json"
      env:
        VERSION: ${{steps.get_version.outputs.version-without-v}}
        URL: ${{ env.project_url }}
        MANIFEST: ${{ env.latest_manifest_url }}
        DOWNLOAD: ${{ env.release_module_url }}
    
    # Create the Module Zip file
    - name: Create Module Archive
      run: |
        # Note that `zip` will only emit warnings when a file or directory doesn't exist, it will not fail.
        zip \
          `# Options` \
          --recurse-paths \
          `# The name of the output file` \
           ./module.zip \
          `# The files that will be included.` \
          module.json \
          README.md \
          CHANGELOG.md \
          LICENSE \
          lang/ \
          packs/ \
          scripts/ \
          styles/ \
          templates/ \
          translations/ \
        # Don't forget to add a backslash at the end of the line for any additional files or directories!
      
    # Update the Github release
    - name: Update Release With Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./module.json, ./module.zip"
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
